### ISSUE TITLE
Sections of view.html

### ISSUE THREAD

**Issue by aso2101** [aso2101/satavahana-inscriptions#17]
Following our conversation this morning, view.html should produce the following sections in `#content-container`:

1. Metadata (`<teiHeader>`)
2. Map (probably a separate function, since the map data will come from the TEI document itself in the case of inscriptions and places, but not in the case of people).
3. Facsimiles (`<facsimile>`) — only for inscriptions (but maybe places will have images as well)
4. Edition (`<div type="edition">`, with tabs as in the EIAD website) — only for inscriptions
5. Translation (`<div type="translation">`) — only for inscriptions
6. Commentary (`<div type="commentary">`) — only for inscriptions; right now this mostly contains prefatory matter, and it might make sense to put it above the edition.
7. Bibliography (`<div type="bibliography">`)
8. Place information (`<place>`) — only for places
9. Person information (`<person>`) — only for persons
10. Relations between people (probably a separate function: see `app:inscriptions-related-to-person-revised`) — only for persons
11. Bibliography item (`<biblStruct>`) — only for bibliography items
12. Records containing this bibliography item (a separate function) — only for bibliography items

These sections ought to be collapsible, eventually (like the map is now)

**Comment by wsalesky** [comment]
@aso2101 Can this issue be closed?
