### ISSUE TITLE
Search functions in teiPublisher branch

### ISSUE THREAD

**Issue by aso2101** [aso2101/satavahana-inscriptions#18]
It appears that the search is no longer separating the text from the metadata and the translation when one of these filters is selected. See:

http://37.252.124.228:8080/exist/apps/SAI/search.html?query=*ye*&filter=text

which returns results from the text, metadata, and translation.

Also the text in the drop-down menu is white, and invisible against the white background unless moused over; this should be changed to black.

**Comment by wsalesky** [comment]
@aso2101 
This seems to be working as expected to me. 
See:  http://37.252.124.228:8080/exist/apps/SAI/search.html?query=Pa%E1%B9%ADha%C3%AF%E1%B9%87ik%C4%81&filter=metadata

vrs.

http://37.252.124.228:8080/exist/apps/SAI/search.html?query=Pa%E1%B9%ADha%C3%AF%E1%B9%87ik%C4%81&filter=translation

Perhaps I need some additional test searches?

**Comment by aso2101** [comment]
That search term probably only matches the translation because the text of SaE33 contains a different string.

I tried with "year" ("ye*" etc.), which shouldn't occur in the text search, but does. The second result gives hits from the teiHeader, too.

Generally it looks like anything that matches the translation will match the text as well.

**Comment by wsalesky** [comment]
Yes, the translation is contained in the text. What should the text be
searching? I think the XQuery is simply not applying the limits you expect.

**Comment by aso2101** [comment]
I am pretty sure this issue has been resolved.
