### ISSUE TITLE
The model in browse.html, people.html, and places.html

### ISSUE THREAD

**Issue by aso2101** [aso2101/satavahana-inscriptions#19]
I notice that `browse.html` currently calls one important function (`app:browse-get-inscriptions`), which puts all of the documents that match the facets into the model in a variable `hits`. A couple of questions about how the code in `app.xql` works with this data (since I'm beginning to clean up `app.xql`):

- `app:dynamic-map-data` begins looking for things in `hits` that have teo:geo data, but since inscriptions don't have geo:geo data, I'm not sure what this is for... (and it doesn't seem to hurt if I delete it)
- I have changed `app:dynamic-map-data` so that if the model has "hits" (i.e., inscriptions) rather than "places" or "persons" it will only populate the map with places that are the `<origPlace>` of inscriptions (see 4e9563be8eb184c91c8da2a719bfae9254fc24aa — previously it was also putting places on the map that were merely mentioned in each inscription)
- How is `model("data")` used?

**Comment by wsalesky** [comment]
- This may be a holdover, if it doesn't effect the code it is fine to delete it. 

- That seems reasonable. 

- model('data') is where data returned by the query (varies depending on which query is calling it) is stored. TEIPublisher uses the $model('data') to store data passed to the view.html page.

**Comment by wsalesky** [comment]
@aso2101 I think this has been superseded by #22 and #22 .
