### ISSUE TITLE
Adding map to "People" page

### ISSUE THREAD

**Issue by aso2101** [aso2101/satavahana-inscriptions#20]
Does the reference to `model("persons")` in `app:dynamic-map-data` suggest that this will be called on `people.html`? (By the way, It seems that `people.html` gets the data from `model("hits")`, set by `app:browse-get-persons`, so I wonder whether the references to `model("persons")` could be eliminated here.) I do think it makes sense to have the same dynamically-generated map that's on browse.html and places.html. However, I think there should be two (non-exclusive) options on this page for putting places onto the map:

- Places where the matching people (`model("hits")`) are *attested* (i.e., a `<placeName>` that occurs in `<origPlace>`  in the inscription attached to `<person>` in the model)
- Places where the matching people are said to *reside* (i.e., a `<placeName>` that occurs in the `<person>` element, specifically `<residence>`).

I would have both of them enabled by default.

I've just changed `browse-person-facet-def` (affcb14602743a15dfd6d121cf32b326b612392a) to reflect this distinction between place of attestation and place of residence.

I also notice that `model("hits")` has a `<person>` entry that contains both the content of `<person>` (in the data collection) and a list of inscriptions where that person's name occurs. Will this be a problem if and when I replace the XML fragments in contextual/People with complete TEI documents? (It doesn't seem like it, since `model("hits")` right now only graps `<person>`, and not the entire document.)

**Comment by wsalesky** [comment]
The reference to $model("persons") is simply to enable the use of the dynamic map on any of our existing pages. It may be unnecessary.

**Comment by aso2101** [comment]
This is a relatively low-priority issue, but I think it would be useful to have a map that displayed either where people are attested, or where people are said to reside, in `people.html`. I am not sure how to make that work with the current facets---maybe just have buttons in the `map-panel` itself that says "places of attestation" and "places of residence"? (This might be hard, since the map data is taken from the model, and this approach would require re-filtering it.)

**Comment by wsalesky** [comment]
@aso2101 Can I have some sample records showing these relationships?

**Comment by wsalesky** [comment]
@aso2101 I think this can be closed?
