### ISSUE TITLE
Redesign places.html and place.html 

### ISSUE THREAD

**Issue by aso2101** [aso2101/satavahana-inscriptions#22]
Just like what I suggested in #20 for people.html, I think the map on places.html should have two options: to show places where inscriptions are actually found (i.e., all `<placeName>`s that occur in `<origPlace>`) and places that are mentioned in the inscriptions (`<placeName>`s in `<div type="edition">`). Of course not all of the latter are identified, so they won't have `tei:geo` data, but it's still worth making the distinction, I think.

**Comment by aso2101** [comment]
* redo `places.html` on the model of `persons.html` and `bibliography.html`
* create a `place.html` file on the model of `view.html`, `person.html`, and `biblio.html`. as we said, this will merely be a placeholder for now, but the links to places in the database (`/places/Sannati` etc.) should point here.
* use "facets" (actually i think a form will do fine) to filter the hits on the two options mentioned above, viz., "places where inscriptions are found" and "places mentioned in inscriptions" on a "hits" page
* another pseudo-facet: include places-within-places or not (see below)
* other possible facets (i will add in a facet definition file as the encoding of `<place>` evolves): current state, current district?

About **places-within-places**:
* Some **inscription documents** mention in the metadata an additional place (an archaeological site) wtihin the main place (see `data/Pau1.xml` in the data repository). 
* Sometimes these places-within-places are reflected in the **place documents**, where they are encoded as `<place>` elements embedded within a `<place>` element. See `contextual/Places/Kuḍā.xml` for an example.
* I think that the main interfaces for viewing places---`browse.html` and `places.html`---should not display these places-within-places by default. The list should be populated only by the first place mentioned in the inscription metadata (for `browse.html`) or by the top-level `<place>` element (for `places.html`).
* Hence links to these places-within-places should point to the record for the "primary place" (this might require some modifications of `app:rec-link`).
* Nevertheless it may be useful to include these places-within-places in the general list if the user wants, so I suggest a button or check box in the facets window to the left.

**Comment by wsalesky** [comment]
@aso2101 
I added a branch with the code I have been working on today. It is not ready to be merged into the master branch as there are a number of significant changes in `app.xql`. However it does give you a `place.html` page to work with when editing the ODD.

**Comment by wsalesky** [comment]
@aso2101 I would like to make a generic browse function in app.xql, see Persons.html, bibliography.html and Places.html. As you can see with the new additions Persons needs some work on the ODD side, can I leave that to you? (The persons list no longer generates a link, and has some extra data included that should be suppressed.) Places.html will also need some ODD editing.

**Comment by aso2101** [comment]
yes, i'll give it a try and see what ODD changes are necessary.

**Comment by wsalesky** [comment]
We can merge this branch into master if you don't mind. I still need to work on the filters/facets for places and the javascript for the maps. Now all the browse pages share a single function in app.xql.

**Comment by aso2101** [comment]
merged. this streamlines things a lot!

**Comment by wsalesky** [comment]
Still working on this functionality. Added the "Places Mentioned" and "Places Found" psuedo facets. Next up a toggle to show hide places within places.

**Comment by wsalesky** [comment]
Can I have some examples of places within places?

**Comment by aso2101** [comment]
I just restructured some of the place entries, see here:
https://github.com/aso2101/satavahana-inscriptions-data/blob/master/contextual/Places/Pauni.xml
https://github.com/aso2101/satavahana-inscriptions-data/blob/master/contextual/Places/Ku%E1%B8%8D%C4%81.xml

Some of the inscriptions in these places (e.g. Ku1, Pau1) refer to places within places in the `origPlace` information.

**Comment by wsalesky** [comment]
@aso2101 
I think the new branch should handle all the outstanding items on this issue. If so, you may close it. 
The places within places toggle button could probably use some additional css styling.
