### ISSUE TITLE
Bibliography entries under the ODD

### ISSUE THREAD

**Issue by aso2101** [aso2101/satavahana-inscriptions#23]
`bibliography.html` still uses `app:list-bibitems` and `app:bibitems`, which don't do anything except output the unprocessed content of `<biblStruct>`. This should be replaced with TEI Publisher functionality.

Note that Emmanuelle's [site](http://hisoma.huma-num.fr/exist/apps/EIAD/works/EIAD_bibliography.xml?tabs=no&odd=teipublisher.odd) uses a single TEI document as a bibliography (so the bibliography is just view.html with the bibliography file passed to it), whereas we have all of the bibliographic records in separate files. But I think that just means we keep bibliography.html and populate the model with `<biblStruct>` entries from $config:remote-context-root.

I should also admit that I don't exactly understand the parameters `pm-config` functions: what do I need to pass to them? (It seems like a `<biblStruct>` node taken from the model won't do...)

**Comment by wsalesky** [comment]
Should this function in a similar way to the way People are handled (a dynamic browse list, with links to bibliographic records)?
 eg: http://37.252.124.228:8080/exist/apps/SAI/people.html

**Comment by aso2101** [comment]
yes, that was the idea. I could think of filters for the browse list (probably `@type` for book/article/etc; maybe a date slider, since we can access `<date when="etc">`?).

**Comment by aso2101** [comment]
also fyi the PYU-EIAD ODD should define most of the transformations for bibliography entries, so in the function corresponding to `app:person-browse-hits` on the bibliography page, you might just try `pm-config:web-transform` on the `biblStruct` node. (I might have to put some some exceptions in the ODD, though.)

**Comment by wsalesky** [comment]
Initial code up. Still need to add date slider.

**Comment by aso2101** [comment]
I'm testing it now, and it seems that one entry (Rosen Stone 2015) is given a date of "2916" on the slider, although I can't see anything in the TEI that would explain it. Is that happening for you?

**Comment by wsalesky** [comment]
It is in the TEI:
https://github.com/aso2101/satavahana-inscriptions-data/blob/97771be2c20134ca60350a8ccc2e846e1e7e83f3/contextual/Bibliography/Quintanilla2016.xml#L51

**Comment by aso2101** [comment]
yes, you are right, i had the wrong entry. fixed with aso2101/satavahana-inscriptions-data@44547d2.

**Comment by wsalesky** [comment]
Sorry, I noticed it but then forgot to file an issue for it!

**Comment by aso2101** [comment]
I made a few changes so that it uses EM's ODD to display the bibliography items at 79c904216031b6c89b6d5915da8b6d4dd68f7ddb. Use the data at aso2101/satavahana-inscriptions-data@4b36c7d8b026ac51574cb2f7fc4ff269eb99a892 to check it (since this reflects the `@type` used in the EIAD project).

**Comment by aso2101** [comment]
still to do: sort the whole list of entries on `tei:title[@type='short']` if it is there, otherwise on `tei:author[1]//tei:surname`, otherwise on `tei:editor[1]//tei:surname`, otherwise on `tei:title[1]`

**Comment by aso2101** [comment]
Following up on our conversation: I'll change the title of the TEI documents to the short title (and maybe think about getting rid of this redundancy, although that will require changes to EM's ODD), and @wsalesky will try adding options to `bibliography.html` to allow different sorting options (by *publication date*, by *author/editor*, and by *title*).

**Comment by aso2101** [comment]
I am keeping the issue23 branch open, but everything should have been merged into master by now. Feel free to delete it and work from a new branch, or fast-forward to the latest version of master, whenever you add these additional facets/sort options.

**Comment by wsalesky** [comment]
@aso2101  I opened a new issue for adding the sort options. I think we can close this one.

**Comment by aso2101** [comment]
great, will look at #46
