### ISSUE TITLE
Search filters and "full TEI" contextual data

### ISSUE THREAD

**Issue by aso2101** [aso2101/satavahana-inscriptions#25]
I think the current search function must interpret any document that has a TEI root as an inscription:
![screenshot from 2017-06-17 23-58-40](https://user-images.githubusercontent.com/997807/27256559-2bccc196-53b9-11e7-8fc1-4ff908a366ba.png)
where the first is one of the few person entries that I've stored as a full TEI document rather than a fragment with the root `<person>`.

How can we distinguish inscriptions from people/places/bibliography items when the latter will (eventually) be stored as TEI documents as well?

**Comment by wsalesky** [comment]
@aso2101 This seems to be resolved on the latest version, that I just installed? Can you confirm? If not I can take another look.

**Comment by aso2101** [comment]
Yes, this does seem to be fixed.
