### ISSUE TITLE
TEI export for view.html

### ISSUE THREAD

**Issue by aso2101** [aso2101/satavahana-inscriptions#26]
Some of my Sanskritist colleagues are really impressed by the 'TEI Export' feature on [syriaca.org](syriaca.org)—not because it's useful to them, but because it demonstrates that the data is open and accessible and whatnot.

Would it be possible to put a TEI Export button (like the one on the right of the title row on, e.g. http://syriaca.org/person/321) on `view.html`? I imagine it would just output the document that is loaded on `app:load`. It could be called from `app:navigation-title`, I suppose.

**Comment by wsalesky** [comment]
New branch has get TEI function, just needs to be added to the view.html page. Do you want it to replace the XML option in the toolbar? Or would you rather have it somewhere else? 

To retrieve the xml version of a record you just need to add the .xml extension. It should work for all records, inscriptions, persons and bibliographic records.

**Comment by aso2101** [comment]
wonderful. yes, i think it would be easiest to just replace the XML button in the toolbar, although i have to say that i find all of the other functions on the toolbar to be useless.

**Comment by wsalesky** [comment]
We can remove the toolbar, or remove the other items.

**Comment by aso2101** [comment]
Okay, then let's remove the toolbar and put the TEI button near the ID marker at the top-right of the page (perhaps in `app:navigation-title`).

**Comment by wsalesky** [comment]
@aso2101  Okay, I added this on a new branch: 
https://github.com/aso2101/satavahana-inscriptions/tree/issue26

If it looks good to you, you can merge it into master.

**Comment by aso2101** [comment]
great. merged!
