### ISSUE TITLE
Issues with app:load and app:display-node

### ISSUE THREAD

**Issue by aso2101** [aso2101/satavahana-inscriptions#27]
I have been scratching my head about this one, but maybe it will be clearer to you @wsalesky:

On the **most recent version** (0497befb6e26af85fdbbd632c503331b721e1a5e), which I haven't put on the server, it seems that none of the ODD behaviours are being applied at all. 

On the version that is currently installed on the server, some documents like  [SaC14](http://37.252.124.228:8080/exist/apps/SAI/inscription/SaC14) seem to work fine (i.e., they apply the ODD), whereas others, like [SaC13](http://37.252.124.228:8080/exist/apps/SAI/inscription/SaC13) , return the following error:

```
exerr:ERROR XPTY0004: The actual cardinality for parameter 1 does not match the cardinality declared in the function's signature: root($arg as node()?) node()?. Expected cardinality: zero or one, got 2. [at line 1315, column 69, source: /db/apps/SAI/modules/app.xql]
```
I'm not sure what's causing the discrepancy in behavior. Anyway, we want all documents to work like SaC14 on the server.

**Comment by wsalesky** [comment]
This is a cardinality error, the string function is expecting a single value/node but is receiving two. Somewhere in app.xql where root() is called, it is being passed two nodes rather then one. I'm not getting the error, so I'm having some trouble finding which one is causing it. 

Also I installed the latest version of the app and the ODD files seem to be applying as expected. Can you try overwriting the .xar file?

**Comment by wsalesky** [comment]
@aso2101 Is this still an issue?

**Comment by aso2101** [comment]
No, the cardinality error seems to be gone.
