### ISSUE TITLE
Facets on search page

### ISSUE THREAD

**Issue by aso2101** [aso2101/satavahana-inscriptions#39]
* results from `<div type="translation">` are given in the facet list as "div"; they should say "translation"
* i think results from `<div type="edition">` should also say "text" (or "inscription text"?) rather than "inscription"

**Comment by wsalesky** [comment]
@aso2101 Can you give me an example to search that includes a translation, so I can see this?

**Comment by aso2101** [comment]
Okay, I think I have now discovered what's going on.

One issue is that Metadata/Text/Translation is part of the drop-down menu, but not part of the facets on the search page. This was a little confusing: I think they should be unified so that the drop-down menu (and the facets) represent the following options, if possible:
- Inscriptions (all of the below)
  - Text (let's include `<div type="apparatus">` in this as well---I'm not sure if this is a good idea, but it's one way to include variant readings when searching for the text, and I'm increasingly inclined to use an external apparatus)
  - Translation 
  - Commentary (`<div type="commentary">`, formerly included in "metadata.")
  - Metadata (this should also include `<div type="bibliography">` as well as the `<teiHeader>`, since I think it will be confusing to have two bibliography options)
- People
- Places
- Bibliography

Now some of the search results. Searching for "pillar" with the "metadata" filter (http://localhost:8080/exist/apps/SAI/search.html?query=pillar&filter=metadata) includes results from `<div type="commentary">` under the facet "div". The other results (from the support information) are under the facet "inscription", but as noted above, it would be clearer if they were marked as hits from the inscription metadata.

Searching for "pillar" with the "text" filter (http://localhost:8080/exist/apps/SAI/search.html?query=pillar&filter=text) gives more results than the "metadata" filter (47), including the metadata and translation, but since "pillar" by definition shouldn't occur in the text of the inscription, there shouldn't be any results.

Searching for "pillar" with the "translation" filter (http://localhost:8080/exist/apps/SAI/search.html?query=pillar&filter=translation) gives 18 results, which all come from the translation div. However, the facet on the left side says "div."

Searching for "pillar" without selecting a filter seems to combine the text and metadata searches; no "div" results appear in the facets.

**Comment by wsalesky** [comment]
Thanks! That helps. Hope to have it fixed in the next day or two.

**Comment by wsalesky** [comment]
@aso2101 will all the records end up with a TEI root element? Including all Person/Place and Bibliography records?

**Comment by aso2101** [comment]
yes, eventually they will. (bibliographic records already do, and i'll do places next, then people.)

**Comment by wsalesky** [comment]
@aso2101 Do you want person,places and bibliography search filters to only search what is in the tei:body or in the tei:header as well?

**Comment by aso2101** [comment]
Only what is in `<tei:body>` (the header will only contain "curatorial" metadata)

**Comment by wsalesky** [comment]
@aso2101 great. thanks

**Comment by wsalesky** [comment]
Fixes in branch: https://github.com/aso2101/satavahana-inscriptions/tree/issue39

**Comment by wsalesky** [comment]
@aso2101 If this looks right to you you may close this.

**Comment by aso2101** [comment]
Great! The new facets work perfectly, as far as I can tell.

Do you think it would be possible to include text, translation, commentary and metadata as subcategories of "inscription" in the "search filter" drop-down, as noted above? As facets, they could be labelled "inscription text," "inscription translation," "inscription commentary," and "inscription metadata," although this is redundant and I'm open to a better solution.

**Comment by wsalesky** [comment]
I added the additional search filters. Adding them as facets is going to be a little more tricky. I'm still working on it, but let's merge the new branch in as this may take some time.

**Comment by aso2101** [comment]
okay, merged. so far the filters are working as expected (although the search behavior for text is a little tricky---i'll start another issue about it).

**Comment by wsalesky** [comment]
@aso2101 I think this can be closed.
