### ISSUE TITLE
Relations between persons

### ISSUE THREAD

**Issue by aso2101** [aso2101/satavahana-inscriptions#50]
@wsalesky you don't happen to know of anything that will take relational data (like the TEI `<relation>` element or some JSON serialization thereof) and turn it into a nice-looking family tree? I know d3 can do it, and I am looking into https://github.com/ErikGartner/dTree, https://github.com/mrblueblue/d3-react-family-tree, and https://github.com/Yakubovich/descendant_tree, but maybe you have some ideas. In any case we would probably need to convert the TEI `<relation>`s to JSON.

**Comment by wsalesky** [comment]
Do you have a preference for one of the above examples? I have used d3js with TEI data in the past (http://wwwb.library.vanderbilt.edu/exist/apps/srophe/spear/browse.html?view=relations), I'm sure we can write a script to extract the data in the format needed.

**Comment by aso2101** [comment]
I had no idea about SPEAR! Very impressive. For this data, I think something very simple and clean will work, which is why I was inclined to dTree, but it doesn't seem to provide out-of-the-box support for labelling the relationships.

I thought that each "set" of relationships (familiar, pedagogical, etc.) could be displayed in a small panel in person.html (like the "map" panel on place.html). It would also be useful to have links in the SVG diagram to the different people involved.

**Comment by wsalesky** [comment]
Do you have any persons records marked up with relationship information? If so, I can experiment with a few of these to see what we can come up with.

**Comment by wsalesky** [comment]
Same as: https://github.com/aso2101/satavahana-inscriptions/issues/66
