### ISSUE TITLE
Make a page for places

### ISSUE THREAD

**Issue by aso2101** [aso2101/satavahana-inscriptions#51]
We have a working `place.html` but the ODD doesn't do anything with `<place>`s at the moment. Write some behaviours to put in the ODD.

@wsalesky I've assigned myself but feel free to take a stab at this---`Beḍsā.xml` is a good example. Actually, `app:related-inscriptions` is called but doesn't seem to do anything here. We should have a list of all the inscriptions at each site (which we already have in `browse.html`).

**Comment by wsalesky** [comment]
Missing inscriptions added to branch issue51
