### ISSUE TITLE
Search issues: adding the apparatus

### ISSUE THREAD

**Issue by aso2101** [aso2101/satavahana-inscriptions#61]
Add `div[@type='apparatus']` to the list of sections that can be searched under "Inscriptions" in the drop-down menu. (This is a relatively new addition and only a few records have an external apparatus but once the feature is there I can test it using those records.)

**Comment by wsalesky** [comment]
@aso2101 
https://github.com/aso2101/satavahana-inscriptions/issues/39

Suggested adding apparatus to text search. I assume that you would like me to separate them out? Or would you like the 'text' option to search both 'edition' and 'apparatus'  and have the 'apparatus' option only search the apparatus? 

Thanks for the clarification.

**Comment by wsalesky** [comment]
Added apparatus filter. Note, the text filter still searches the apparatus as well.

**Comment by aso2101** [comment]
merged branch 61.
