### ISSUE TITLE
Search issues: problems with searching "Text"

### ISSUE THREAD

**Issue by aso2101** [aso2101/satavahana-inscriptions#62]
I noticed after searching for ghara* and getting a few results, I tried to search for it again and got zero results. It turns out that I got results when searching for "Inscription" but not for "Text" (although the results occurred in `div[@type='edition']`. A few other examples:

- dham* gives 53 results for "Inscription," but zero results for "Text," although most of the results are contained in `div[@type='edition']`
- likewise, deya* gives 112 results for "Inscription," most of which lie in `div[@type='edition']`, but only one result for "Text"

**Comment by wsalesky** [comment]
Fixed. For some reason I had the text filter only search `div[@type='apparatus']` I have added `div[@type='edition']` 

You can close after testing the new code.

**Comment by aso2101** [comment]
Perfect. Merged issue62 into master with 5fc00cf091f15a7bba2b2b4ab38a7a3c4dd9003b.
