### ISSUE TITLE
"Show on map" missing for some places in browse.html

### ISSUE THREAD

**Issue by aso2101** [aso2101/satavahana-inscriptions#64]
@wsalesky I think that in order for the "Show on map" button to appear, the `@xml:id` of a `<place>` (which provides the heading in the list) needs to be identical to the label that the place is given on the map, which is derived from `<placeName>` (specifically the first occurrence of an "ancient" placeName, and otherwise the modern placeName). This has meant that some places (like Bhaja and Bedse) have lost their "show on map" button when I've added additional `<placeName>` elements. 

I now think that it's better to leave as an "editorial decision" how particular places will be referred to, i.e., whether to use ancient or modern names. For `<place>` elements that already have full TEI records the preferred name of the place will be in the `<title>` element; otherwise, it will be the first occurrence of `<placeName>` (which will match the title when it is added). Could you change `smap:create-data` and `app:browse-hits` to use this information for the name of the place, and check that the "Show on map" functionality in browse.html is restored?

**Comment by wsalesky** [comment]
@aso2101  
Fixed on ithub.com/aso2101/satavahana-inscriptions/compare/issue64
Please check that this meets expectations and then merge and close issue.
