### ISSUE TITLE
Sorting with numbers

### ISSUE THREAD

**Issue by aso2101** [aso2101/satavahana-inscriptions#67]
@wsalesky is there a way to sort the inscriptions on browse.html so that we have (e.g.) 9, 10, 11 rather than 1, 10, 11, 12, 13, 2, etc.? (See the order of inscriptions at http://localhost:8080/exist/apps/SAI/browse.html?fq=;fq-Place:pl:Bh%C4%81j%C4%81)

**Comment by aso2101** [comment]
![screenshot from 2017-08-19 11-47-58](https://user-images.githubusercontent.com/997807/29488212-9512311c-8506-11e7-81f4-e7d186adb751.png)

**Comment by wsalesky** [comment]
Change default behavior to sort on the ID

**Comment by wsalesky** [comment]
Fixed on branch: https://github.com/aso2101/satavahana-inscriptions/tree/issue67
