### ISSUE TITLE
error with "show on map" when there are places within places

### ISSUE THREAD

**Issue by aso2101** [aso2101/satavahana-inscriptions#73]
![screenshot from 2017-09-17 08-49-58](https://user-images.githubusercontent.com/997807/30520963-467e4abe-9b85-11e7-9d73-a679c04d8a58.png)

(the same thing happens with Pauni, where there are just two places within places)

**Comment by wsalesky** [comment]
Link? To problem page?

**Comment by aso2101** [comment]
sorry!

http://localhost:8080/exist/apps/SAI/browse.html

**Comment by wsalesky** [comment]
Thanks!

**Comment by wsalesky** [comment]
Okay, branch issue73 should resolve this. Let me know if you continue to have issues.

**Comment by wsalesky** [comment]
Actually this is not yet fixed. Just found a new flavor of the bug.

**Comment by wsalesky** [comment]
Okay I think that covers all the issues.
